### ISSUE TITLE
两个ogbn数据集的参数

### ISSUE THREAD

**Issue by CuAlB** [LirongWu/HGMD#1]
您好，很抱歉再次打扰您，您是否方便提供arxiv和products这两个数据集的参数，我是一名知识蒸馏领域的初学者，目前在尝试复现您的实验。已经在前六个均取得了不错的效果，但是在arxiv数据集上效果与论文内的不太一样，我是直接通过修改传入的data超参数来调用best_parameter.json中的arxiv参数，通过观察csv文件参数传入均正确，接下来复现products时发现json文件里没有这个数据集对应的参数集合，期待与您进一步交流，谢谢。

**Comment by LirongWu** [comment]
Large-scale datasets are more susceptible to randomness caused by different hardware platforms. The hyperparameters we provide are also just for reference, and we strongly recommend that you follow the instructions in “Appendix B. Implementation Details” to find a more suitable combination of hyperparameters using NNI with the provided hyperparameter search space.

**Comment by CuAlB** [comment]
[PerformMetrics (7).csv](https://github.com/user-attachments/files/17810557/PerformMetrics.7.csv)
您好，我按您的建议使用附录B的范围用NNI调试，硬件是一块4090，但效果不佳，但在设置lr学习率为0.0005而非论文中提到的0.005后性能有显著提升，并发现500的max epoch不能让学生MLP收敛，增大max epoch到3000后MLP收敛且准确率达到了71.5，甚至超过了您在论文中写的71.09，但考虑到了您为了保证与NOSMOG等蒸馏方法公平作比较一定设置了一些实验细节，所以仅能提供一些参考作用。我想进一步了解您在两个obg上的实验细节，如果可以的话我也希望了解一下obgn-products上的参数配置，我可以进一步调参

**Comment by CuAlB** [comment]
抱歉，昨天我的参数调试忽略了低学习率带来的过拟合，今天我将lr回调到论文中给出的数字0.05得到了相同的效果71%，我猜测可能是max_epoch提高的作用，我观察到该参属下原来的500epoch学生MLP还未收敛就结束了，总之问题得到了解决，谢谢您的耐心，如果您再次运行arxiv上的实验时遇到相似的问题可以考虑修改json文件中的最大epoch至1000左右，学生训练大约会在800步左右早停
